### ISSUE TITLE
Add dockerfile, and releases to dockerhub

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cqlsh#13]
as @tzach suggested, 
we should package cqlsh also as docker image, 
and upload it to dockerhub as part of releasing to pypi

**Comment by mykaul** [comment]
I wonder if something like https://containerssh.io/ (only CQLsh) might be relevant for serverless

**Comment by fruch** [comment]
> I wonder if something like https://containerssh.io/ (only CQLsh) might be relevant for serverless

once we have docker image, should be doable, but you might want to track it on the cloud UI
