### ISSUE TITLE
artifact oel8 test failed in cql 

### ISSUE THREAD

**Issue by Annamikhlin** [scylladb/scylla-cqlsh#26]
**artifacts-oel81-test** failed with error:

```
10:34:31  /etc/bashrc: line 99: TMOUT: readonly variable
10:34:31  /etc/bashrc: line 100: TMOUT: readonly variable
10:34:31  bash: /usr/bin/cqlsh: Permission denied
```

link to failed job: 
https://jenkins.scylladb.com/job/scylla-master/job/artifacts-offline-install/job/artifacts-oel81-test/176/

**Comment by Annamikhlin** [comment]
@syuu1228 please take a look

/cc @yaronkaikov

**Comment by fruch** [comment]
@syuu1228 sounds like issue with umask we were having with oel8 before.

I wonder where it's should be handled, in core it was in scylla_setup, how it was handled in tools ?

**Comment by syuu1228** [comment]
I guess this is very similar issue as https://github.com/scylladb/scylladb/issues/10752.
To fix this, each executables should be set permission explicitly like `install -m755 "$script" "$destdir"` or `chmod $script`.

also see: https://github.com/scylladb/scylladb/commit/13caac7ae6e408f54e0ae8641697348b706a6328
