### ISSUE TITLE
cqlsh doesn't provide context sensitive help for service levels

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla-cqlsh#43]
Maybe it doesn't also for other scylla-specific CQL features,
but I noticed on 2021.1.6 that it's context sensitive tab-completion/help doesn't include e.g.
`LIST SERVICE_LEVEL;` or `LIST ALL SERVICE_LEVELS;` or `DROP SERVICE_LEVEL;`

Cc @eliransin

**Comment by eliransin** [comment]
@Jadw1 added this to your queue because it is service level related (no label for it in this current repo).

**Comment by fruch** [comment]
@eliransin @Jadw1 
FYI I have a PR which address this:
https://github.com/scylladb/scylla-cqlsh/pull/48

A review of it would be helpful, @Jadw1 you can that PR over if you want to make any changes to it.

**Comment by Jadw1** [comment]
> A review of it would be helpful, @Jadw1 you can that PR over if you want to make any changes to it.

I don't know cqlsh code very well so probably I don't have anything to add.
But I'll look into the PR and check if it covers all of the cases (if i recall correctly you can write both `LIST SERVICE_LEVEL` and `LIST SERVICE LEVEL`)
