### ISSUE TITLE
Cqlsh in Scylla Docker does not use `.cqlshrc`

### ISSUE THREAD

**Issue by RoDmitry** [scylladb/scylla-cqlsh#62]
I have updated Scylla Docker image from 5.2.11 to 5.4.0 and now I have an error with cqlsh:
```
~# cqlsh
Connection error: ('Unable to connect to any servers', {'127.0.0.1:9042': ConnectionRefusedError(111, "Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused")})

~# cat .cqlshrc
[connection]
hostname = 172.18.0.2

~# cqlsh 172.18.0.2
// works
```
I don't understand where it takes an ip from, and also Scylla not listening for a localhost seems strange.

dir `~/.cassandra/` is empty.

Docker-compose:
```
scylla:
  image: scylladb/scylla
  command: --smp 1 --memory 512M --overprovisioned 1 --api-address 0.0.0.0 --authenticator PasswordAuthenticator --authorizer CassandraAuthorizer
```

Removing `--api-address 0.0.0.0` does not help.

**Comment by mykaul** [comment]
Dup of https://github.com/scylladb/scylladb/issues/16329 ?

**Comment by mykaul** [comment]
Closing as dup - let's continue the conversation over the other issue.
