### ISSUE TITLE
CQLsh fails to redirect COPY output to STDOUT

### ISSUE THREAD

**Issue by hopugop** [scylladb/scylla-cqlsh#71]
When using the redirect output to STDOUT on COPY, I consistently get an error:

```
# cqlsh -v
cqlsh 6.2.0
# cqlsh -e 'COPY system.config TO STDOUT WITH HEADER = true;'
<stdin>:1:'NoneType' object is not callable
# 
```

Result, per the manual, should be CQLsh redirecting the output to stdout. 
\Worked fine on `cqlsh 5.0.1` as shipped with Scylla Enterprise `2023.1.4`. Fails with `6.2.0` as shipped with `2024.1.0`.

**Comment by fruch** [comment]
We already fixed that

It's not yet merged into scylla core

**Comment by fruch** [comment]
https://github.com/scylladb/scylla-cqlsh/commit/387f769c5f9784154a11efc6b131e75509682416

Is the fix...

**Comment by fruch** [comment]
already fixed and backported to the relevant branches
