### ISSUE TITLE
Version print is broken, and always default to 6.2.0

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cqlsh#81]
the import of the version file happens too early, before cqlshlib location is in path, and fails

so it works when installing the python package, but no how it's installed/usage by our packaging

**Comment by mykaul** [comment]
https://github.com/scylladb/scylla-cqlsh/blame/3baa678c240e2860d66ac05ddb9071d303244c3d/bin/cqlsh.py#L54 I assume?

**Comment by fruch** [comment]
> https://github.com/scylladb/scylla-cqlsh/blame/3baa678c240e2860d66ac05ddb9071d303244c3d/bin/cqlsh.py#L54 I assume?

yes
