### ISSUE TITLE
/opt/scylladb/share/cassandra/bin/cqlsh.py mistakenly run on /usr/bin/python3

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla-cqlsh#97]
While I'm trying to reproduce https://github.com/scylladb/scylladb/issues/19775, I got different error.
When I run /opt/scylladb/share/cassandra/bin/cqlsh.py instead of /usr/bin/cqlsh, I hit following error message:
```
$ sudo /opt/scylladb/share/cassandra/bin/cqlsh.py 

Python Cassandra driver not installed, or not on PYTHONPATH.
You might try "pip install cassandra-driver".

Python: /usr/bin/python3
Module load path: ['/opt/scylladb/share/cassandra/libexec', '/opt/scylladb/share/cassandra/bin', '/opt/scylladb/share/cassandra/libexec', '/home/ec2-user/scylla-6.1.0~dev', '/usr/lib64/python36.zip', '/usr/lib64/python3.6', '/usr/lib64/python3.6/lib-dynload', '/usr/lib64/python3.6/site-packages', '/usr/lib/python3.6/site-packages']

Error: No module named 'cassandra'
```

Seems like it is mistakenly executed on /usr/bin/python3, therefore not able to find cassandra module.

It is because we specify `#!/usr/bin/python3` on shebang of the script.
To run python3 script on scylla-python3 we should use `#!/usr/bin/env python3`.

Test environment is following:
AMI: ami-04aa1c37e1e5393a2
OS: Oracle Linux 8.1
Unified package: https://downloads.scylladb.com/unstable/scylla/master/relocatable/2024-07-15T15:17:20Z/scylla-unified-6.1.0~dev-0.20240715.144794a95216.x86_64.tar.gz

But likely the error is not OEL8 specific problem.

**Comment by syuu1228** [comment]
Ah, this is duplicated issue of https://github.com/scylladb/scylla-cluster-tests/issues/7995

**Comment by syuu1228** [comment]
No, it looks similar but different.
This issue is about calling incorrect python interpreter.

https://github.com/scylladb/scylla-cluster-tests/issues/7995 is running /usr/bin/cqlsh directly, and says `Python: /opt/scylladb/share/cassandra/bin/../../../python3/bin/python3`.
It probably calling correct python interpreter but failed to find cassandra module.
Maybe PYTHONPATH is incorrect?

**Comment by fruch** [comment]
> No, it looks similar but different. This issue is about calling incorrect python interpreter.
> 
> [scylladb/scylla-cluster-tests#7995](https://github.com/scylladb/scylla-cluster-tests/issues/7995) is running /usr/bin/cqlsh directly, and says `Python: /opt/scylladb/share/cassandra/bin/../../../python3/bin/python3`. It probably calling correct python interpreter but failed to find cassandra module. Maybe PYTHONPATH is incorrect?

I think it's a permission issue... of scylla-python3 as written in https://github.com/scylladb/scylladb/issues/19775

when running the command with sudo, it does work...
